stages:
  - test
  - scan      # 新增：专门用来放代码扫描的阶段，排在 test 后面
  - build

# 1. 后端测试任务
backend-test:
  stage: test
  image: python:3.12
  script:
    - cd backend
    - pip install -r requirements.txt
    - pip install pytest httpx pytest-cov
    - pytest --cov=app --cov-report=xml:coverage.xml --cov-report=term-missing
  artifacts:
    paths:
      - backend/coverage.xml
  only:
    - main
    - merge_requests

# 2. SonarQube 代码扫描任务
sonarqube-check:
  stage: scan
  needs: ["backend-test"]
  image: sonarsource/sonar-scanner-cli:4.6
  script:
    - cd backend
    # 下面这行是缝合了学校秘钥和覆盖率报告的终极版
    - sonar-scanner -Dsonar.projectKey=WhatTheDogDoing:WhatTheDogDoing -Dsonar.sources=app -Dsonar.host.url=https://sonarqube.spring26b.secoder.net -Dsonar.login=00bfcdd4ec718487c16a7959940c0976b1f57d8a -Dsonar.python.coverage.reportPaths=coverage.xml
  allow_failure: true
  only:
    - main
    - merge_requests

# 3. 前端代码规范检查
frontend-lint:
  stage: test
  image: node:20
  script:
    - cd frontend
    - npm install
    - npm run lint
  only:
    - main
    - merge_requests

# 4. 前端构建任务
build-frontend:
  stage: build
  image: node:20
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
  only:
    - main