server {
    listen 80;
    root /opt/app/dist;

    location / {
        try_files $uri $uri.html $uri/index.html /index.html;
    }

    location /auth/ {
        proxy_pass http://backend-dyno.whatthedogdoing.secoder.local;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://backend-dyno.whatthedogdoing.secoder.local;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
