server {
    listen 80;
    root /opt/app/dist;
    
    location / {
        # 配合 React/Vue 的单页面应用路由回退机制
        try_files $uri $uri.html $uri/index.html /index.html;
    }

    # 代理到正确的内网域名，并且不需要写 8000 端口了
    location /api/ {
        proxy_pass http://backend-dyno.whatthedogdoing.secoder.local/; 
    }
}